import { NamedEntity } from "@/types"

export const data: NamedEntity[] = [
  {
    "label": "futuristic",
    "aliases": {
      "en": [
        "city of the future",
        "synthetic food",
        "artifical life",
        "computer",
        "computers",
        "replicator",
        "replicators",
        "self-replicator",
        "self-replicators",
        "replicant",
        "replication",
        "dna strand",
        "dna strands",
        "oxygen tank",
        "memory wipe",
        "grid with vectors",
        "hum of the machine",
        "dna programming",
        "simulation",
        "virtual",
        "offworld",
        "off world",
        "recombination",
        "alkylating",
        "mutagen",
        "robot",
        "robotic",
        "robotics",
        "robot dog",
        "robot police",
        "high-voltage tethers",
        "through space",
        "galaxy",
        "galactic",
        "gravitational",
        "gravitational wave",
        "gravitational waves",
        "graphene",
        "tycho",
        "tycho base",
        "lunar hangar",
        "lunar rover",
        "space shuttle",
        "enogenic",
        "repressor protein",
        "I'm a clone",
        "you're a clone",
        "he is a clone",
        "she is a clone",
        "vortex",
        "biomechanics",
        "spaceship",
        "space ship",
        "star ship",
        "starship",
        "mothership",
        "spacesuit",
        "spacesuits",
        "lunar roving",
        "roving vehicle",
        "mapping computer",
        "space helmet",
        "space helmets",
        "astronaut",
        "astronauts",
        "inter-stellar",
        "hyper-drive",
        "range of the planet",
        "landing on the planet",
        "orbital insertion",
        "probe retract system",
        "landing probe",
        "planet's surface",
        "hostile planet",
        "depressurization",
        "pepressurization",
        "space vacuum",
        "laser pistol",
        "laser pistols",
        "servomoteur",
        "android",
        "cyberspace",
        "air lock",
        "airlock",
        "solar system",
        "solar systems",
        "teleportation",
        "reactor",
        "nuclear reactor",
        "reactors",
        "asteroids",
        "asteroid belt",
        "light year",
        "light years",
        "diagnostic coffin",
        "laser beam",
        "last door",
        "blast doors",
        "alien creature",
        "alien device",
        "cryosleep",
        "hypersleep",
        "science fiction",
        "science-fiction",
        "sometime in the future",
      ]
    },
    prompts: {
      character: [],
      location: [],
      transition: [],
      time: [],
      era: ["futuristic"],
      lighting: ["dimly lit"],
      weather: [],
      action: [],
      music: ["electronic"],
      sound: [],
      dialogue: [],
      style: ["futuristic"],
      camera: [],
    }
  },
  {
    "label": "antiquity",
    "aliases": {
      "en": [
        // "antiquity",
        "oracle",
        "atlar",
        "nobilis",
        //"tunic",
        //"toga",
        "calceus",
        "calcei",
        "proletarii",
        "patrician",
        "patricians",
        "domus",
        "sparta",
        "spartan",
        "spartans",
        "spartan warrior",
        "plebeian",
        "plebeians",
        "plebs",
        "plebis",
        // "roman",
       //  "romans",
        "roman emperor",
        "julius caesar",
        "greek warrior",
        "greek warriors",
        "Peloponnesus",
        "punic war",
        "anatolian",
        "athenian",
        "athenians",
        "ephor",
        "ephors",
        "phocian",
        "phocians",
        "greek hoplite",
        "greek hoplites",
        "hoplite",
        "hoplites",
        "spartan hoplite",
        "spartan hoplites",
        "spartanhoplite",
        "spartanhoplites",
        "trireme",
        "triremes",
        "euclid",
        "archimedes",
        "theron",
        "stelios",
        "astinos",
        "lakonia",
        "daxos",
        "ephialtes",
        "phalanx",
        "bronze helmet",
        "bronze helmets",
        "bronze sword",
        "bronze swords",
        "bronze shield",
        "bronze shields",
        "bronze arrow",
        "bronze arrows",
        "Pleistarchos",
        "kythera",
        "Antikythera",
        "Agiad",
        "Agiads",
        "Eurypontid",
        "Eurypontids",
        "Eurysthenes",
        "Procles",
        "Heracles",
        "Trojan War",
        "Rex Sacrorum",
        "Galum",
        "Gallum",
        "Triumvir",
        "Triumvirs",
        "Xerxes",
        "Persia",
        "Persian",
        "Leonidas",
        "Menelaus",
        "Cleomenes",
        "Pausanias",
        "Chilon",
        "of sparta",
        "Lysander",
        "Agnes",
        "Agesilaus",
        "Echestratus",
        "Agis",
        "Leotychidas",
        "Alcaeus",
        "Alexandros",
        "Anaxander",
        "Teleclus",
        "Eunomus",
        "Archelaus",
        "Myles",
        "Gorgo",
        "vesuvio",
        "caius",
        "dilios",
        "aurelius",
        "Aristotle",
        "Lucretia",
        "Alexander",
        "Aurelia",
        "Titus",
        "Augustus",
        "Clodius",
       //  "Marcus",
        "Julius",
        "Romulus",
        "Claudius",
        "Lucius",
        "Cassandra",
        "Valeria",
        "Maximus",
        "Nero",
        "Aeschylus",
        "Cicero",
        "Agatha",
        "Aesop",
        "Aelius",
        "Aetius",
        "Lazarus",
        "Tiberius",
        "Neptune",
        "Demetrius",
        "Zeus",
        "Lelex",
        "Myles",
        "Eurotas",
        "Hercules",
        "Atreids",
        "Dorians",
        "Perseus",
        "Pater familias",
        "cives",
        "peregrina",
        "peregrinus",
        "orator"
      ]
    },
    prompts: {
      character: [],
      location: [],
      transition: [],
      time: [],
      era: ["antiquity", "roman, greek and spartan empire"],
      lighting: [],
      weather: [],
      action: [],
      music: ["old harp music"],
      sound: [],
      dialogue: [],
      style: ["antiquity", "roman, greek and spartan empire"],
      camera: [],
    }
  },
  {
    "label": "1800-1900 western",
    "aliases": {
      "en": [
        "Western",
        "cowboy",
        "cowboys",
        "saddles",
        "saddle",
        "frontiersman",
        "frontiersmen",
        "outlaws",
        "town mashal",
        "constable",
        "posse",
        "california gold rush",
        "californios",
        "Far West",
        "American frontier",
        "Old West",
        "Wild West",
        "Thomas Jefferson",
        "Louisiana Purchase",
        "western territories",
        "Arizona settlers",
        "the great plains",
        "oregon trail",
        "mormon trail",
        "bozeman trail",
        "california trail",
        "oklahoma land rush",
        "desert land act",
        "buffalo hunter",
        "bison hunter",
        "bison hunt",
        "buffalo hunt",
        "suffragists",
        "buffalo soldier",
        "american bison",
        "cowtown",
        "cowtowns",
        "jeffersonian",
        "homesteading",
        "yeoman farmer",
        "homesteader",
        "homesteaders",
        "stagecoach",
        "wagonmaster",
        "wagon trail",
        "mormon war",
        "utah war",
        "pony express",
        "Abraham Lincoln",
        "sioux warrior",
        "sioux warriors",
        "1860",
        "1861",
        "1862",
        "1863",
        "1865",
        "1865",
        "1866",
        "1867",
        "1868",
        "1869",
        "1870",
        "1871",
        "1872",
        "1873",
        "1874",
        "1875",
        "1876",
        "1877",
        "1878",
        "1879",
        "1880",
        "1881",
        "1882",
        "1883",
        "1884",
        "1885",
        "1886",
        "1887",
        "1888",
        "1889",
        "1890",
        "1891",
        "1892",
        "1893",
        "1894",
        "1895",
        "1896",
        "1897",
        "1898",
        "1899",
        "1900",
        "1901",
        "1902",
        "1903",
        "1904",
        "1905",
        "1906",
        "1907",
        "1908",
        "1909"
      ]
    },
    prompts: {
      character: [],
      location: [],
      transition: [],
      time: [],
      era: ["1800s", "1880", "farewest"],
      lighting: [],
      weather: [],
      action: [],
      music: ["western music"],
      sound: [],
      dialogue: [],
      style: ["american", "western", "dusty"],
      camera: ["color footage"],
    }
  },
  {
    "label": "1914-1918",
    "aliases": {
      "en": [
        "first world war",
        "world war 1",
        "world war",
        "the great war",
        "1914",
        "1915",
        "1916",
        "1917",
        "1918",
        "WW1",
        "Western Front",
        "French trench",
        "German trench",
        "German shells"
      ]
    },
    prompts: {
      character: [],
      location: [],
      transition: [],
      time: [],
      era: ["during WW1"], // ["1914", "1915", "1916", "1917", "1918"],
      lighting: [],
      weather: [],
      action: [],
      music: ["1910 jazz"],
      sound: [],
      dialogue: [],
      style: ["color footage", "in color"],
      camera: [],
    }
  },
  {
    "label": "1938-1945",
    "aliases": {
      "en": [
        "world war 2",
        "world war II",
        "second world war",
        "1939",
        "1940",
        "1941",
        "1942",
        "1943",
        "1944",
        "1945",
        "WW2",
        "WWII",
        "Western Front",
        "German shells"
      ]
    },
    prompts: {
      character: [],
      location: [],
      transition: [],
      time: [],
      era: ["during WW2"], // ["1939", "1940", "1944", "1945"],
      lighting: [],
      weather: [],
      action: [],
      music: ["1940 jazz, 40s"],
      sound: [],
      dialogue: [],
      style: ["40s"],
      camera: ["color footage", "in color"],
    }
  },
  {
    "label": "The 50s",
    "aliases": {
      "en": [
        "the fifties",
        "50s",
        "1950",
        "1951",
        "1952",
        "1953",
        "1954",
        "1955",
        "1956",
        "1957",
        "1958",
        "1959",
        "Eisenhower era"
      ]
    },
    prompts: {
      character: [],
      location: [],
      transition: [],
      time: [],
      era: ["during the 50s"], // ["1950", "1952", "1954", "1955", "1957", "1958", "1959"],
      lighting: [],
      weather: [],
      action: [],
      music: ["50s"],
      sound: [],
      dialogue: [],
      style: ["50s", "fifties"],
      camera: ["color footage", "in color"],
    }
  },
  {
    "label": "The 60s",
    "aliases": {
      "en": [
        "the sixties",
        "60s",
        "1960",
        "1961",
        "1962",
        "1963",
        "1964",
        "1965",
        "1966",
        "1967",
        "1968",
        "1969",
        "JFK",
        "jfk era"
      ]
    },
    prompts: {
      character: [],
      location: [],
      transition: [],
      time: [],
      era: ["during the 60s"], // ["1960", "1962", "1964", "1965", "1967", "1968", "1969"],
      lighting: [],
      weather: [],
      action: [],
      music: ["60s"],
      sound: [],
      dialogue: [],
      style: ["60s", "sixties"],
      camera: ["color footage", "in color"],
    }
  },
  {
    "label": "The 70s",
    "aliases": {
      "en": [
        "the seventies",
        "70s",
        "1970",
        "1971",
        "1972",
        "1973",
        "1974",
        "1975",
        "1976",
        "1977",
        "1978",
        "1979",
        "nixon era"
      ]
    },
    prompts: {
      character: [],
      location: [],
      transition: [],
      time: [],
      era: ["during the 70S"], // ["1970", "1972", "1974", "1975", "1977"],
      lighting: [],
      weather: [],
      action: [],
      music: ["70s"],
      sound: [],
      dialogue: [],
      style: ["70s", "seventies"],
      camera: ["color footage", "in color"],
    }
  },
  {
    "label": "The 80s",
    "aliases": {
      "en": [
        "the eighties",
        "80s",
        "1980",
        "1981",
        "1982",
        "1983",
        "1984",
        "1985",
        "1986",
        "1987",
        "1988",
        "1989"
      ]
    },
    prompts: {
      character: [],
      location: [],
      transition: [],
      time: [],
      era: ["during the 80s"], // ["1980", "1982", "1984", "1986"],
      lighting: [],
      weather: [],
      action: [],
      music: ["80s"],
      sound: [],
      dialogue: [],
      style: ["80s", "eighties"],
      camera: [],
    }
  },
  {
    "label": "The 90s",
    "aliases": {
      "en": [
        "the nineties",
        "90s",
        "1990",
        "1991",
        "1992",
        "1993",
        "1994",
        "1995",
        "1996",
        "1997",
        "1998",
        "1999",
        "clinton era"
      ]
    },
    prompts: {
      character: [],
      location: [],
      transition: [],
      time: [],
      era: ["during the 1990s"], // ["1990", "1992", "1994", "1995", "1996", "1998"],
      lighting: [],
      weather: [],
      action: [],
      music: ["90s"],
      sound: [],
      dialogue: [],
      style: ["90s", "nineties"],
      camera: [],
    }
  },
  {
    "label": "The 2000s",
    "aliases": {
      "en": [
        "2000s",
        "2000",
        "2001",
        "2002",
        "2003",
        "2004",
        "2005",
        "2006",
        "2007",
        "2008",
        "2009",
        "George Walker Bush",
        "George Bush",
        "43rd POTUS",
      ]
    },
    prompts: {
      character: [],
      location: [],
      transition: [],
      time: [],
      era: ["2005 style"], // ["2000", "2001", "2002", "2007", "2008"],
      lighting: [],
      weather: [],
      action: [],
      music: ["2000s"],
      sound: [],
      dialogue: [],
      style: ["the 2000s"],
      camera: [],
    }
  },
  {
    "label": "contemporary",
    "aliases": {
      "en": [
        "present day",
        "cash register",
       // "streetlight",
        //"streetlights",
        "security camera",
        //"gasoline",
        "gas station",
        "security footage",
        "plastic bottle",
        //"telephone pole",
        "security console",
        //"stethoscope",
        //"chevy",
        //"christmas lights",
        //"headphone",
        //"headphones",
        //"hearing aid",
        //"driveway",
        //"car",
        //"cars",
        //"truck",
        //"trucks",
        //"bike",
        //"motorbike",
        //"phone",
        "phone company",
        //"telephone",
        //"electric",
        //"electricity",
        //"electric lines",
        "tv",
        //"television",
       // "radio",
        //"toaster",
        "microwave",
        //"coffee machine",
       //  "train",
        // "train station",
        // "camera", <- no, this is used by the script itself!
       //  "photo",
      ]
    },
    prompts: {
      character: [],
      location: [],
      transition: [],
      time: [],
      era: ["contemporary"],
      lighting: [],
      weather: [],
      action: [],
      music: ["contemporary music"],
      sound: [],
      dialogue: [],
      style: ["contemporary"],
      camera: [],
    }
  },
  {
    "label": "2000s, 2010s, 2015, 2020, 2022",
    "aliases": {
      "en": [
        "internet",
        "email",
        "e-mail",
        "website",
        "social network",
        "GPS",
        "iphone",
        "ipad",
        "android phone",
        "smartphone",
        "laptop",
        "cellphone",
      ]
    },
    prompts: {
      character: [],
      location: [],
      transition: [],
      time: [],
      era: ["contemporary", "modern", "2018", "2022"],
      lighting: [],
      weather: [],
      action: [],
      music: ["modern music"],
      sound: [],
      dialogue: [],
      style: ["contemporary", "modern", "2018", "2022"],
      camera: [],
    }
  },
]