export { resolveSegment as resolveSegmentUsingHuggingFace } from "./huggingface"
export { resolveSegment as resolveSegmentUsingComfyReplicate } from "./comfy-replicate"
export { resolveSegment as resolveSegmentUsingReplicate } from "./replicate"
export { resolveSegment as resolveSegmentUsingComfyComfyIcu } from "./comfy-comfyicu"
export { resolveSegment as resolveSegmentUsingFalAi } from "./falai"
export { resolveSegment as resolveSegmentUsingModelsLab } from "./modelslab"
export { resolveSegment as resolveSegmentUsingStabilityAi } from "./stabilityai"