import {
  ClapWorkflow,
  ClapWorkflowEngine,
  ClapWorkflowCategory,
  ClapWorkflowProvider,
} from '@aitube/clap'

// ------------------------------------------------------------------------------
// if a user is already using one of those workflows and you change its settings,
// they will have to reselect it in the UI for changes to be taken into account.
//
// -> we can create a ticket to fix this
// ------------------------------------------------------------------------------

// those placeholder workflows allow the user to de-select a step
// eg. disable face swapping
export const noneWorkflows: ClapWorkflow[] = [
  {
    id: 'none://image/face-swap',
    label: 'No workflow',
    description: '',
    tags: [],
    author: '',
    thumbnailUrl: '',
    nonCommercial: false,
    engine: ClapWorkflowEngine.DEFAULT,
    category: ClapWorkflowCategory.IMAGE_FACESWAP,
    provider: ClapWorkflowProvider.NONE,
    data: '',
    schema: '',
    inputFields: [],
    inputValues: {},
  },
  {
    id: 'none://video/face-swap',
    label: 'No workflow',
    description: '',
    tags: [],
    author: '',
    thumbnailUrl: '',
    nonCommercial: false,
    engine: ClapWorkflowEngine.DEFAULT,
    category: ClapWorkflowCategory.VIDEO_FACESWAP,
    provider: ClapWorkflowProvider.NONE,
    data: '',
    schema: '',
    inputFields: [],
    inputValues: {},
  },
  {
    id: 'none://image/upscaling',
    label: 'No workflow',
    description: '',
    tags: [],
    author: '',
    thumbnailUrl: '',
    nonCommercial: false,
    engine: ClapWorkflowEngine.DEFAULT,
    category: ClapWorkflowCategory.IMAGE_UPSCALING,
    provider: ClapWorkflowProvider.NONE,
    data: '',
    schema: '',
    inputFields: [],
    inputValues: {},
  },
  {
    id: 'none://video/upscaling',
    label: 'No workflow',
    description: '',
    tags: [],
    author: '',
    thumbnailUrl: '',
    nonCommercial: false,
    engine: ClapWorkflowEngine.DEFAULT,
    category: ClapWorkflowCategory.VIDEO_UPSCALING,
    provider: ClapWorkflowProvider.NONE,
    data: '',
    schema: '',
    inputFields: [],
    inputValues: {},
  },
  {
    id: 'none://video/lipsync',
    label: 'No workflow',
    description: '',
    tags: [],
    author: '',
    thumbnailUrl: '',
    nonCommercial: false,
    engine: ClapWorkflowEngine.DEFAULT,
    category: ClapWorkflowCategory.VIDEO_LIPSYNC,
    provider: ClapWorkflowProvider.NONE,
    data: '',
    schema: '',
    inputFields: [],
    inputValues: {},
  },
  {
    id: 'none://image/generation',
    label: 'No workflow',
    description: '',
    tags: [],
    author: '',
    thumbnailUrl: '',
    nonCommercial: false,
    engine: ClapWorkflowEngine.DEFAULT,
    category: ClapWorkflowCategory.IMAGE_GENERATION,
    provider: ClapWorkflowProvider.NONE,
    data: '',
    schema: '',
    inputFields: [],
    inputValues: {},
  },
  {
    id: 'none://video/generation',
    label: 'No workflow',
    description: '',
    tags: [],
    author: '',
    thumbnailUrl: '',
    nonCommercial: false,
    engine: ClapWorkflowEngine.DEFAULT,
    category: ClapWorkflowCategory.VIDEO_GENERATION,
    provider: ClapWorkflowProvider.NONE,
    data: '',
    schema: '',
    inputFields: [],
    inputValues: {},
  },
]
