import {
  ClapWorkflow,
  ClapWorkflowEngine,
  ClapWorkflowCategory,
  ClapWorkflowProvider,
} from '@aitube/clap'

import {
  genericHeight1024,
  genericHeight2048,
  genericImage,
  genericPrompt,
  genericVideo,
  genericWidth1024,
  genericWidth2048,
} from '../common/defaultValues'

export const cohereWorkflows: ClapWorkflow[] = [
  {
    id: 'cohere://command-r-plus',
    label: 'Command R+',
    description: '',
    tags: ['command-r'],
    author: 'Cohere',
    thumbnailUrl: '',
    engine: ClapWorkflowEngine.REST_API,
    category: ClapWorkflowCategory.ASSISTANT,
    provider: ClapWorkflowProvider.COHERE,
    data: 'command-r-plus',
    inputFields: [genericPrompt],
    inputValues: {
      prompt: genericPrompt.defaultValue,
    },
  },
  {
    id: 'cohere://command-r',
    label: 'Command R',
    description: '',
    tags: ['command-r'],
    author: 'Cohere',
    thumbnailUrl: '',
    engine: ClapWorkflowEngine.REST_API,
    category: ClapWorkflowCategory.ASSISTANT,
    provider: ClapWorkflowProvider.COHERE,
    data: 'command-r',
    inputFields: [genericPrompt],
    inputValues: {
      prompt: genericPrompt.defaultValue,
    },
  },
  {
    id: 'cohere://command',
    label: 'Command',
    description: '',
    tags: ['command'],
    author: 'Cohere',
    thumbnailUrl: '',
    nonCommercial: false,
    canSupportLora: false,
    engine: ClapWorkflowEngine.REST_API,
    category: ClapWorkflowCategory.ASSISTANT,
    provider: ClapWorkflowProvider.COHERE,
    data: 'command',
    schema: '',
    inputFields: [genericPrompt],
    inputValues: {
      prompt: genericPrompt.defaultValue,
    },
  },
  {
    id: 'cohere://command-light',
    label: 'Command Light',
    description: '',
    tags: ['command', 'light'],
    author: 'Cohere',
    thumbnailUrl: '',
    nonCommercial: false,
    canSupportLora: false,
    engine: ClapWorkflowEngine.REST_API,
    category: ClapWorkflowCategory.ASSISTANT,
    provider: ClapWorkflowProvider.COHERE,
    data: 'command-light',
    schema: '',
    inputFields: [genericPrompt],
    inputValues: {
      prompt: genericPrompt.defaultValue,
    },
  },
  {
    id: 'cohere://command-nightly',
    label: 'Command (nightly)',
    description: '',
    tags: ['command', 'nightly'],
    author: 'Cohere',
    thumbnailUrl: '',
    nonCommercial: false,
    canSupportLora: false,
    engine: ClapWorkflowEngine.REST_API,
    category: ClapWorkflowCategory.ASSISTANT,
    provider: ClapWorkflowProvider.COHERE,
    data: 'command-nightly',
    schema: '',
    inputFields: [genericPrompt],
    inputValues: {
      prompt: genericPrompt.defaultValue,
    },
  },
  {
    id: 'cohere://command-light-nightly',
    label: 'Command Light (nightly)',
    description: '',
    tags: ['command', 'light', 'nightly'],
    author: 'Cohere',
    thumbnailUrl: '',
    nonCommercial: false,
    canSupportLora: false,
    engine: ClapWorkflowEngine.REST_API,
    category: ClapWorkflowCategory.ASSISTANT,
    provider: ClapWorkflowProvider.COHERE,
    data: 'command-light-nightly',
    schema: '',
    inputFields: [genericPrompt],
    inputValues: {
      prompt: genericPrompt.defaultValue,
    },
  },
]
